In [1]:
import numpy as np

# Writing efficient Python code using array broadcasting

Suppose we want to multiply the matrix $n$-th row of a matrix by a number $n$, i.e. multiply 1st row by 1, 2nd row by 2 and so on. 

For example:

$$
\begin{pmatrix}
1 & 2 \\
3 & 4
\end {pmatrix}
\rightarrow
\begin{pmatrix}
1 & 2 \\
6 & 8
\end {pmatrix}
$$

We can do this using two different methods:
1. Using a for loop
2. Using array broadcasting

Let's look at the required time for these two methods.

## Method 1: For Loop

In [2]:
z = np.arange(1,5).reshape(2,2)
z

array([[1, 2],
       [3, 4]])

In [3]:
for i in range(2):
    z[i,:] = z[i,:]*(i+1)
z

array([[1, 2],
       [6, 8]])

In [4]:
%%timeit
for i in range(2):
    z[i,:] = z[i,:]*(i+1)

3.16 µs ± 292 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Large array

In [5]:
large_z = np.arange(1,2001).reshape(-1,2)
large_z

array([[   1,    2],
       [   3,    4],
       [   5,    6],
       ...,
       [1995, 1996],
       [1997, 1998],
       [1999, 2000]])

In [6]:
for i in range(1000):
    large_z[i,:] = large_z[i,:]*(i+1)
large_z

array([[      1,       2],
       [      6,       8],
       [     15,      18],
       ...,
       [1991010, 1992008],
       [1995003, 1996002],
       [1999000, 2000000]])

In [7]:
%%timeit
for i in range(1000):
    large_z[i,:] = large_z[i,:]*(i+1)

1.4 ms ± 24.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Method 2: Array Broadcasting

In [8]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [9]:
y = np.arange(1,3).reshape(2,1)
y

array([[1],
       [2]])

In [10]:
print(x*y)

[[1 2]
 [6 8]]


In [11]:
%timeit x*y

1.06 µs ± 34.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Large array

In [12]:
large_x = np.arange(1,2001).reshape(-1,2)
large_x

array([[   1,    2],
       [   3,    4],
       [   5,    6],
       ...,
       [1995, 1996],
       [1997, 1998],
       [1999, 2000]])

In [13]:
large_y = np.arange(1,1001).reshape(-1,1)


In [14]:
large_x*large_y

array([[      1,       2],
       [      6,       8],
       [     15,      18],
       ...,
       [1991010, 1992008],
       [1995003, 1996002],
       [1999000, 2000000]])

In [15]:
%timeit large_x*large_y

12.7 µs ± 255 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
