In [1]:
import numpy as np

# Writing efficient Python code using array broadcasting

Suppose we want to multiply the matrix $n$-th row of a matrix by a number $n$, i.e. multiply 1st row by 1, 2nd row by 2 and so on. 

For example:

$$
\begin{pmatrix}
1 & 2 \\
3 & 4
\end {pmatrix}
\rightarrow
\begin{pmatrix}
1 & 2 \\
6 & 8
\end {pmatrix}
$$

We can do this using two different methods:
1. Using a ***for*** loop
2. Using array broadcasting

Let's look at the required time for these two methods.

# Small array

## Method 1: For Loop

In [2]:
z = np.arange(1,5).reshape(2,2)
z

array([[1, 2],
       [3, 4]])

In [3]:
for i in range(2):
    z[i,:] = z[i,:]*(i+1)
z

array([[1, 2],
       [6, 8]])

In [4]:
%%timeit -o -r 1000 -n 1 -q

for i in range(2):
    z[i,:] = z[i,:]*(i+1)

<TimeitResult : 4.2 µs ± 4.71 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

## Method 2: Array Broadcasting

In [5]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [6]:
y = np.arange(1,3).reshape(2,1)
y

array([[1],
       [2]])

In [7]:
print(x*y)

[[1 2]
 [6 8]]


In [8]:
%%timeit -o -r 1000 -n 1 -q

x*y

<TimeitResult : 1.61 µs ± 748 ns per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

# Large array

## Method 1: For Loop

In [9]:
large_z = np.arange(1,2001).reshape(-1,2)
large_z

array([[   1,    2],
       [   3,    4],
       [   5,    6],
       ...,
       [1995, 1996],
       [1997, 1998],
       [1999, 2000]])

In [10]:
for i in range(1000):
    large_z[i,:] = large_z[i,:]*(i+1)
large_z

array([[      1,       2],
       [      6,       8],
       [     15,      18],
       ...,
       [1991010, 1992008],
       [1995003, 1996002],
       [1999000, 2000000]])

In [11]:
%%timeit -o -r 1000 -n 1 -q

for i in range(1000):
    large_z[i,:] = large_z[i,:]*(i+1)

<TimeitResult : 1.45 ms ± 140 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

## Method 2: Array Broadcasting

In [12]:
large_x = np.arange(1,2001).reshape(-1,2)
large_x

array([[   1,    2],
       [   3,    4],
       [   5,    6],
       ...,
       [1995, 1996],
       [1997, 1998],
       [1999, 2000]])

In [13]:
large_y = np.arange(1,1001).reshape(-1,1)


In [14]:
large_x*large_y

array([[      1,       2],
       [      6,       8],
       [     15,      18],
       ...,
       [1991010, 1992008],
       [1995003, 1996002],
       [1999000, 2000000]])

In [15]:
%%timeit -o -r 1000 -n 1 -q

large_x*large_y

<TimeitResult : 17.6 µs ± 9.38 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

# Vectorization

Suppose we want to apply the following function to each element of the array:


$$
    y= 
\begin{cases}
    x-thr,& \text{if } x\geq thr\\
    x+thr,              & \text{otherwise}
\end{cases}
$$

We can do this using three different methods:
1. Using a ***for*** loop
2. Using the ***map*** function
3. Using ***np.vectorize***

Let's look at the required time for these three methods.

In [16]:
def myFunc(x,threshold):
    if x>threshold:
        return x-threshold
    else:
        return x+threshold

# Small array

In [17]:
x_arr = np.arange(10)
y_arr = np.empty_like(x_arr)
thr = 5

## Method 1: For loop

In [18]:
for i in range(len(x_arr)):
    y_arr[i] = myFunc(x_arr[i],thr)
print(y_arr)

[ 5  6  7  8  9 10  1  2  3  4]


In [19]:
%%timeit -o -r 1000 -n 1 -q

for i in range(len(x_arr)):
    y_arr[i] = myFunc(x_arr[i],thr)

<TimeitResult : 6.15 µs ± 1.33 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

## Method 2: map

In [20]:
y_arr = list(map(lambda x: myFunc(x,thr),x_arr))
print(y_arr)

[5, 6, 7, 8, 9, 10, 1, 2, 3, 4]


In [21]:
%%timeit -o -r 1000 -n 1 -q

y_arr = list(map(lambda x: myFunc(x,thr),x_arr))

<TimeitResult : 5.64 µs ± 1.32 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

## Method 3: np.vectorize

In [22]:
vectorizedFunc = np.vectorize(myFunc)
y_arr = vectorizedFunc(x_arr,thr)
print(y_arr)

[ 5  6  7  8  9 10  1  2  3  4]


In [23]:
%%timeit -o -r 1000 -n 1 -q

y_arr = vectorizedFunc(x_arr,thr)

<TimeitResult : 16.6 µs ± 11.2 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

# Large array

In [24]:
x_arr = np.arange(1000)
y_arr = np.empty_like(x_arr)
thr = 500

## Method 1: For loop

In [25]:
%%timeit -o -r 1000 -n 1 -q

for i in range(len(x_arr)):
    y_arr[i] = myFunc(x_arr[i],thr)

<TimeitResult : 551 µs ± 78.8 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

## Method 2: map

In [26]:
%%timeit -o -r 1000 -n 1 -q

y_arr = list(map(lambda x: myFunc(x,thr),x_arr))

<TimeitResult : 427 µs ± 77.6 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>

## Method 3: np.vectorize

In [27]:
%%timeit -o -r 1000 -n 1 -q

y_arr = vectorizedFunc(x_arr,thr)

<TimeitResult : 194 µs ± 77.4 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)>